amazon:
  endpoint: https://s3.ap-south-1.amazonaws.com
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  bucket-name: aws-spring-s3
system:
  proxy:
    host: http://172.28.5.70
    port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
